apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    labels:
      stage: prd
      app: ai-backend
    name: haiqv-ir-ai-backend
    namespace: argocd
  spec:
    destination:
      namespace: app-haiqv-ir
      server: https://10.42.186.81:6443
    project: default
    source:
      path: prd
      repoURL: http://gitea.gitea:3000/Haiqv-IR/haiqv-ir-ai-backend-deploy
      targetRevision: master
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    labels:
      stage: prd
      app: web-au
    name: haiqv-ir-au
    namespace: argocd
  spec:
    destination:
      namespace: app-haiqv-ir
      server: https://10.42.186.81:6443
    project: default
    source:
      path: prd
      repoURL: http://gitea.gitea:3000/Haiqv-IR/haiqv-ir-au-deploy
      targetRevision: master
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    labels:
      stage: prd
      app: web-be
    name: haiqv-ir-be
    namespace: argocd
  spec:
    destination:
      namespace: app-haiqv-ir
      server: https://10.42.186.81:6443
    project: default
    source:
      path: prd
      repoURL: http://gitea.gitea:3000/Haiqv-IR/haiqv-ir-be-deploy
      targetRevision: master
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    labels:
      stage: prd
      app: web-fe
    name: haiqv-ir-web
    namespace: argocd
  spec:
    destination:
      namespace: app-haiqv-ir
      server: https://10.42.186.81:6443
    project: default
    source:
      path: prd
      repoURL: http://gitea.gitea:3000/Haiqv-IR/haiqv-ir-web-deploy
      targetRevision: master
    syncPolicy:
      syncOptions:
      - CreateNamespace=true
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    labels:
      stage: prd
      app: web-fe
    name: haiqv-ir-web-tpd
    namespace: argocd
  spec:
    destination:
      namespace: app-haiqv-ir
      server: https://10.42.186.81:6443
    project: default
    source:
      path: tpd
      repoURL: http://gitea.gitea:3000/Haiqv-IR/haiqv-ir-web-deploy
      targetRevision: master
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
kind: List
metadata:
  resourceVersion: ""
