apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: dev-haiqv-ir-web-listener
spec:
  serviceAccountName: sa-pipeline-trigger
  triggers:
    - name: dev-haiqv-ir-web-trigger
      interceptors:
        - name: "CEL filter: only master brancher pushed"
          ref:
            name: "cel"
          params:
          - name: "filter"
            value: "body.ref in ['refs/heads/master']"
      bindings:
        - ref: dev-haiqv-ir-web-binding
      template:
        ref: dev-haiqv-ir-web-template
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: dev-haiqv-ir-web-binding
spec:
  params:
    - name: git-revision
      value: $(body.after)
    - name: git-repository-url
      value: $(body.repository.clone_url)
    - name: git-repo-name
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: dev-haiqv-ir-web-template
spec:
  params:
    - name: git-revision
      description: The git revision
    - name: git-repository-url
      description: The git repository url
    - name: git-repo-name
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        labels:
          stage: dev
          app: haiqv-ir-web
          from: trigger
        generateName: dev-haiqv-ir-web-trigger-
      spec:
        serviceAccountName: sa-pipeline-runner
        pipelineRef:
          name: buildah
        params:
          - name: build-stage
            value: dev
          - name: git-repo-name
            value: $(tt.params.git-repo-name)
          - name: git-branch
            value: $(tt.params.git-revision)
          - name: insecure-registry
            value: "true"
          - name: git-url
            value: "http://gitea.gitea:3000/Haiqv-IR"
          - name: image-url
            value: "docker.hanwhasystem.co.kr"
          - name: gitops-repo-name
            value: $(tt.params.git-repo-name)-deploy
          - name: gitops-branch
            value: "master"
          - name: gitops-url
            value: "http://gitea.gitea:3000/Haiqv-IR"
          - name: argo-app-name
            value: "dev-haiqv-ir-web"
        workspaces:
        - name: source
          persistentvolumeclaim:
            claimName: pvc-build
        - name: gitops
          emptyDir: {}
