apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    app: fileserver
    stage: qa
  generateName: qa-hone-aihub-go-filserver-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: build-buildah-qa
  params:
  - name: build-stage
    value: qa
  - name: git-url
    value: "http://gitea.ai-dev/argo"
  - name: git-repo-name
    value: hone-aihub-go
  - name: git-branch
    value: master
  - name: tls-verify
    value: "false"
  - name: image-url
    value: "docker.ai-dev"
  - name: image-extra-url
    value: "aidt-qa-llm-registry.ncr.gov-ntruss.com"
  - name: image-name
    value: "aidt-llm-fileserver"
  - name: dockerfile 
    value: "./fileserver/Dockerfile-fileserver"
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-build
    subPath: $(context.pipelineRun.name)
