apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
  name: build-gradle-jib
  namespace: build
spec:
  params:
  - default: kw-mvn
    name: git-repo-name
    type: string
  - default: main
    name: git-branch
    type: string
  - default: "false"
    name: insecure-registry
    type: string
  - name: git-url
    type: string
  - name: image-url
    type: string
  - name: gitops-url
    type: string
  - name: argo-app-name
    type: string
  - name: gitops-repo-name
    type: string
  - name: gitops-branch
    type: string
  - default: dev
    name: build-stage
    type: string
  - default: kustomization.yaml
    name: build-manifest
    type: string
  tasks:
  - name: generate-id
    params:
    - name: base-version
      value: $(params.build-stage)
    taskRef:
      kind: Task
      name: generate-build-id
  - name: clone-sources
    params:
    - name: url
      value: $(params.git-url)/$(params.git-repo-name)
    - name: revision
      value: $(params.git-branch)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: source
  - name: build-image
    params:
    - name: IMAGE
      value: $(params.image-url)/$(params.git-repo-name):$(tasks.generate-id.results.build-id)
    - name: INSECUREREGISTRY
      value: $(params.insecure-registry)
    runAfter:
    - clone-sources
    taskRef:
      kind: Task
      name: jib-gradle
    workspaces:
    - name: source
      workspace: source
  - name: deploy
    params:
    - name: argo-app-name
      value: $(params.argo-app-name)
    - name: gitops-url
      value: $(params.gitops-url)/$(params.gitops-repo-name)
    - name: gitops-revision
      value: $(params.gitops-branch)
    - name: image-url
      value: $(params.image-url)
    - name: build-id
      value: $(tasks.generate-id.results.build-id)
    - name: build-stage
      value: $(params.build-stage)
    - name: build-manifest
      value: $(params.build-manifest)
    runAfter:
    - build-image
    taskRef:
      kind: Task
      name: deploy
    workspaces:
    - name: gitops
      workspace: gitops
  workspaces:
  - name: source
  - name: gitops
