apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy
spec:
  params:
  - name: argo-app-name
  - name: gitops-url
    default: "http://192.168.121.151:30079/scm/kbdev/kb-dev-deployments.git"
  - name: gitops-revision
  - name: image-url
  - name: build-id
  - name: build-stage
  - name: deploy-manifest
    default: "kustomization.yaml"
  - name: argo-url
    default: "argocd-server.argocd:443"

  workspaces:
  - name: gitops

  stepTemplate:
    env:
    - name: ARGOCD_SERVER
      value: $(params.argo-url)
    - name: ARGO_USER_ID
      valueFrom:
        secretKeyRef:
          name: argocd-credentials-secret
          key: argocd-user-id
    - name: ARGO_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: argocd-credentials-secret
          key: argocd-user-password
  steps:
  - name: git-checkout
    image: 10.42.186.95:5000/alpine/git:v2.26.2
    workingDir: "$(workspaces.gitops.path)"
    script: |
      #!/usr/bin/env sh
      git init
      echo "---------------------"
      echo $(params.gitops-url)
      echo "---------------------"
      git remote add origin $(params.gitops-url)
      git fetch --depth 1 origin $(params.gitops-revision)
      git checkout $(params.gitops-revision)
  - name: update-yaml
    image: 10.42.186.95:5000/alpine/git:v2.26.2
    workingDir: "$(workspaces.gitops.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      echo "updating image to $(inputs.params.image-url)/$(inputs.params.argo-app-name):$(inputs.params.build-id)"
      ls -al .
      sed -i "s|newTag:.*$|newTag: $(params.build-id)|" $(params.build-stage)/$(params.deploy-manifest)
  - name: commit-push-changes-gitops
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.gitops.path)"
    script: |
      #!/usr/bin/env sh
      set -e
      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "Tekton Pipeline"
      git add .
      git commit --allow-empty -m "[tekton] updating image to $(inputs.params.build-id)"
      git push origin $(params.gitops-revision)
  - name: wait-for-argocd-rollout
    image: 10.42.186.95:5000/argoproj/argocd:v2.4.8
    script: |
      #!/usr/bin/env sh
      #set -e
      argocd login $ARGOCD_SERVER --username $ARGO_USER_ID --password $ARGO_USER_PASSWORD --insecure --plaintext
      argocd app sync $(inputs.params.argo-app-name) --insecure --plaintext
      #argocd app wait $(inputs.params.argo-app-name) --sync --health --operation --insecure

