apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: generate-build-id
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "buildid"
spec:
  description: >-
    Given a base version, this task generates a unique build id by appending
    the base-version to the current timestamp.    
  params:
    - name: base-version
      description: Base product version
      type: string
      default: "dev"
  results:
    - name: timestamp
      description: Current timestamp
    - name: build-id
      description: ID of the current build
  steps:
    - name: get-timestamp
      image: bitnami/minideb
      script: |
        #!/usr/bin/env bash
        ts=$(TZ=Asia/Seoul date "+%y%m%d-%H%M%S")
        echo "Current Timestamp: ${ts}"
        echo ${ts} | tr -d "\n" | tee $(results.timestamp.path)        
    - name: get-buildid
      image: bitnami/minideb
      script: |
        #!/usr/bin/env bash
        ts=`cat $(results.timestamp.path)`
        id=`echo $RANDOM | md5sum | head -c 8`
        buildId=$(inputs.params.base-version)-${ts}-${id}
        echo ${buildId} | tr -d "\n" | tee $(results.build-id.path)        
