apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-buildah
spec:
  params:
    - name: git-repo-name 
      default: kw-mvn
    - name: git-branch
      default: master
    - name: tls-verify
      default: "false"
    - name: git-url
    - name: image-url 
    - name: image-extra-url 
    - name: image-extra-tag 
      default: "latest"
    - name: image-name 
    - name: dockerfile
    - name: context
      default: .
    - name: gitops-repo-name
    - name: gitops-revision
    - name: build-stage
      default: "dev"
    - name: deploy-manifest
  workspaces:
    - name: source 
    - name: gitops 
  tasks:
    - name: generate-id
      taskRef:
        name: generate-build-id
      params:
        - name: base-version
          value: $(params.build-stage)
    - name: clone-sources
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)/$(params.git-repo-name)
        - name: revision
          value: $(params.git-branch)
      workspaces:
        - name: output
          workspace: source
    - name: build-image
      taskRef:
        name: buildah
      runAfter:
        - clone-sources
      params:
        - name: IMAGE
          value: $(params.image-url)/$(params.image-name):$(tasks.generate-id.results.build-id)
        - name: IMAGE_EXTRA
          #value: $(params.image-extra-url)/$(params.image-name):$(params.image-extra-tag)
          value: $(params.image-extra-url)/$(params.image-name):$(tasks.generate-id.results.build-id)
        - name: TLSVERIFY
          value: $(params.tls-verify)
        - name: DOCKERFILE
          value: $(params.dockerfile)
        - name: CONTEXT
          value: $(params.context)
      workspaces:
        - name: source
          workspace: source
    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build-image
      params:
        - name: argo-app-name
          value: $(params.build-stage)-$(params.git-repo-name)-$(params.image-name)
        - name: gitops-url
          value: $(params.git-url)/$(params.gitops-repo-name) 
        - name: image-url
          value: $(params.image-url)
        - name: gitops-revision
          value: $(params.gitops-revision)
        - name: build-id
          value: $(tasks.generate-id.results.build-id)
        - name: deploy-manifest
          value: $(params.deploy-manifest)
      workspaces:
        - name: gitops
          workspace: gitops
