---
apiVersion: v1
kind: Secret
metadata:
    name: docker-auth-ai-dev
    annotations:
      tekton.dev/docker-0: docker.ai-dev
type: kubernetes.io/basic-auth
stringData:
    username: "admin"
    password: "1"
---
apiVersion: v1
kind: Secret
metadata:
    name: docker-auth-ktbook-dev
    annotations:
      tekton.dev/docker-1: aidt-dev-atr-registry.ncr.gov-ntruss.com
type: kubernetes.io/basic-auth
stringData:
    username: "13DB29CDF371CE62F256"
    password: "A9082AB15DF7767FDDD4449C6C05DB3DE29227C0"
---
apiVersion: v1
kind: Secret
metadata:
    name: docker-auth-ktbook-qa
    annotations:
      tekton.dev/docker-1: aidt-qa-llm-registry.ncr.gov-ntruss.com
type: kubernetes.io/basic-auth
stringData:
    username: "13DB29CDF371CE62F256"
    password: "A9082AB15DF7767FDDD4449C6C05DB3DE29227C0"
---
apiVersion: v1
kind: Secret
metadata:
    name: docker-auth-ktbook-prd
    annotations:
      tekton.dev/docker-1: aidt-prd-llm-registry.ncr.gov-ntruss.com
type: kubernetes.io/basic-auth
stringData:
    username: "13DB29CDF371CE62F256"
    password: "A9082AB15DF7767FDDD4449C6C05DB3DE29227C0"
---
apiVersion: v1
kind: Secret
metadata:
  name: gitea-auth
  annotations:
    tekton.dev/git-0: http://gitea.ai-dev
type: kubernetes.io/basic-auth
stringData:
  username: "argo"
  password: "12345678"
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: sa-pipeline-runner
secrets:
    - name: docker-auth-ai-dev
    - name: docker-auth-ktbook-dev
    - name: docker-auth-ktbook-qa
    - name: docker-auth-ktbook-prd
    - name: gitea-auth
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pipeline-trigger
secrets:
  - name: kube-api-secret
---

apiVersion: v1
kind: Secret
metadata:
  name: kube-api-secret
  annotations:
    kubernetes.io/service-account.name: sa-pipeline-trigger
type: kubernetes.io/service-account-token
---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: build
  name: role-pipeline-trigger
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "triggers", "triggerbindings", "triggertemplates", "clustertriggerbindings", "clusterinterceptors", "interceptors"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"] # secrets are only needed for Github/Gitlab interceptors
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
  # Permisnions to create EL pods
  - apiGroups: ["extensions", "apps", ""]
    resources: ["services", "deployments", "pods"]
    verbs: ["get", "create", "update", "patch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-bidning-pipeline-trigger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-pipeline-trigger
subjects:
  - kind: ServiceAccount
    name: sa-pipeline-trigger
    namespace: build
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: sa-pipeline-trigger
  namespace: build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-eventlistener-clusterbinding-tekton-pipelines-ns
subjects:
- kind: ServiceAccount
  name: sa-pipeline-trigger
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
